<?php

namespace AppBundle\Repository;
use AppBundle\AppBundle;
use AppBundle\Entity\Event;
use AppBundle\Entity\EventModification;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findUpcoming($timestamp = null)
    {
        $start = new \DateTime();
        if ($timestamp) {
            $start->setTimestamp($timestamp);
        }

        $qb = $this->createQueryBuilder('events')
            ->where('events.startDate < :start')
            ->setParameter('start', $start)
            ->orderBy('events.eventStartTime', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
