<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Reservation;
use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
    public function findUpcoming()
    {
        $start = new \DateTime();
        $qb = $this->createQueryBuilder('event')
            ->where('event.startDate < :start')
            ->setParameter('start', $start)
            ->orderBy('event.eventStartTime', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
