<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Event;
use AppBundle\Entity\Reservation;
use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
    public function findEventReservations(Event $event)
    {
        $qb = $this->createQueryBuilder('reservation')
            ->where('reservation.event = :event')
            ->setParameter('event', $event);

        return $qb->getQuery()->getResult();
    }
}
